### ISSUE TITLE
opening wrong name

### ISSUE THREAD

**Issue by sloslo4** [framps/GeoLite2xtables#2]
`open /tmp/cfd497081164/GeoLite2-Country-CSV_20190219/GeoLite2-Country-Blocks-IPv4.csv: no such file or directory`

...and such errors temporary fix by:

46a47,48
```
>         IPV4fk           = "GeoLite2-Country-CSV_20190820/GeoLite2-Country-Blocks-IPv4.csv"
>         IPV6fk           = "GeoLite2-Country-CSV_20190820/GeoLite2-Country-Blocks-IPv6.csv"
118c120
<               ParseCountryBlocks(cfd+"/"+IPV4csv, countries)
---
>               ParseCountryBlocks(cfd+"/"+IPV4fk, countries)
121c123
<               ParseCountryBlocks(cfd+"/"+IPV6csv, countries)
---
>               ParseCountryBlocks(cfd+"/"+IPV6fk, countries)

```

**Comment by framps** [comment]
Thank you very much for reporting the issue. Fixed in https://github.com/framps/GeoLite2xtables/commit/ef6ada95ac6c8f1c06ebe9f1ceda50c66ca3edb3. The csv name now is extracted from the zip file to remove the hard coded filename. 

Please verify :wink:

**Comment by sloslo4** [comment]
Thank you for this software! Sadly but xtables now discounted in debian (10 / buster) (need compile from src)
But that software working good and fast.
Have a nice day!
